### ISSUE TITLE
Entity Names are switching

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#10]
I had the situation a couple of times that the sensor names are switching. I can’t tell when this exactly happens but what happens is that one time the sensor is called `sensor.heizkreis_heizkreise_heizkreis_1_aussentemperatur_aktuell_hzk1` And another time the same sensor gets the name `sensor.hydraulik_aussentemperatur_aktuell`. The other sensor is then getting the state ‚unavailable‘ and is not available. Every time this happens I switch the sensor in my dashboard and it is back working but then suddenly the switch is done again. The same happens with `sensor.heizkreis_heizkreise_heizkreis_1_warmwassertemperatur_aktuell` and `sensor.heizkreis_heizkreise_heizkreis_2_warmwassertemperatur_aktuell`

**Comment by erikkastelec** [comment]
I would suggest you look into conditional card or custom:monster-card as explained in this [thread](https://community.home-assistant.io/t/show-entities-conditionally-only-show-if-they-exist/130452). This would probably be the easiest temporary fix.

I am working on #9, which should fix this issue.

**Comment by dm82m** [comment]
Okay not so important, will wait for #9
