### ISSUE TITLE
Version 1.5.10 still shows 1.5.9 as version number

### ISSUE THREAD

**Issue by M3d1c5** [erikkastelec/hass-WEM-Portal#100]
Fix is released in the newest version (1.5.10)

_Originally posted by @erikkastelec in https://github.com/erikkastelec/hass-WEM-Portal/issues/96#issuecomment-2395578038_
            
Hi Erik,

thanks for the solution to problem #96.
Since so many people were affected, you probably had some stress.
You may have overlooked adjusting the version number.
Version 1.5.10 still shows 1.5.9 for me.

Kind regards
Christian

**Comment by erikkastelec** [comment]
Thank you both for reminding and fixing this. Release should have proper version now.

**Comment by dm82m** [comment]
@M3d1c5 just re-install through hacs and restart your server to get it updated
