### ISSUE TITLE
Reverse Engineer WEM-KNX 

### ISSUE THREAD

**Issue by Dud3z** [erikkastelec/hass-WEM-Portal#105]
Hi Guys,

i bought myself a WEM-KNX Gateway do get some Data onto the KNX Bus. Is there any chance we can intercept the Communication between the KNX Gateway and the WEM Device? 

i'd be happy to help.

**Comment by erikkastelec** [comment]
As I do not have KNX Gateway I can't work on this so I am closing it as not planned. Maybe you can find some support on Home Assistant community form. 

If anyone is willing to contribute, they are welcome.
