### ISSUE TITLE
Any plans to use long term statistics for the sensor?

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#11]
HA added long term statistics with 2021.8.0 and increased the support for integrations with 2021.9.0 - any plans in adding that here to this plugin to be able to check some historical data?

See: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by erikkastelec** [comment]
Looks like this should be quite easy to implement. Will take a look after I finish #9.

**Comment by dm82m** [comment]
I implemented that for my custom_component. will check if it works and if so I will create a PR here...
