### ISSUE TITLE
Delayed reset of sensor statistic-elektr_energie_tag has impact on sensor value

### ISSUE THREAD

**Issue by Bertk** [erikkastelec/hass-WEM-Portal#115]
I noticed sensor statistic-elektr_energie_tag is set to zero at 00:42:25. This delay has impact on the statistic value.
I guess other statistic values are impacted as well. I am not sure whether this is related to UTC (API) and local time (HA instance) or just delayed update actions.

![Verlauf_elektr_energie_tag](https://github.com/user-attachments/assets/c9fee543-f776-4969-9140-6e8cc5888db9)

|date|reset time|
|---|---|
|2.12.2024|00:41.10|  
|3.12.2024|00:57.05|
|4.12.2024|00:44:33|
|7.12.2024|00:55:20|
|8.12.2024|00:42:25|

**Comment by erikkastelec** [comment]
This is dependant on implementation on side of Weishaupt, so I do not see a way in which I could implement a solution for this. Especially as the reset times are not consistent.

Closing as not planned
