### ISSUE TITLE
Point for decimals instead of comma

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#20]
Hey guys,

Floats are split by point in HA and not in comma. We use comma here due to wemportal is using comma. We should convert them before storing.

Best,
Dirk

**Comment by erikkastelec** [comment]
Where exactly is the comma used? To my knowledge every entity uses appropriate data type (float) for it's value. If I am mistaken, let me know and I will fix this with the next update.

**Comment by dm82m** [comment]
![21648849-CC72-43A9-A846-4719D0E14BD9](https://user-images.githubusercontent.com/736311/161193012-3765cc58-f3c2-4aa8-8acf-177427d43fd2.jpeg)

![254193F6-B06B-4851-A267-FF31C796F925](https://user-images.githubusercontent.com/736311/161193032-8806ef3d-720e-4939-8023-61aa31086285.jpeg)

in this example you see that float values for this component are stored with comma. And it should be with point.

**Comment by erikkastelec** [comment]
Interesting, will account for this. I have all the values with dots even on wemportal website.

**Comment by dm82m** [comment]
with german language settings on wemportal its comma separated. that is why I said, that we should try to convert the values to python float datatype and fallback to string if its not castable.

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/736311/161236356-8d5e5595-29e3-4a8d-8ec8-257dbc5bbecf.png">
