### ISSUE TITLE
api_scan_interval = scan_interval

### ISSUE THREAD

**Issue by mathiaslehmann** [erikkastelec/hass-WEM-Portal#24]
Hello, I just noticed that the "api_scan_interval" runs in the same interval as the "scan_interval". The API is currently queried every 30 minutes but should actually be every 5 minutes.
![config](https://user-images.githubusercontent.com/16978467/164300567-a35f0983-b8a3-4bd8-b031-a59fba1a2465.png)

**Comment by erikkastelec** [comment]
Missed that, thanks.
There were some changes with naming while combining both sources of data, which caused this.
 I am testing a solution and will update if everything seems fine.

**Comment by erikkastelec** [comment]
Should be fixed now. Let me know if I missed something.

**Comment by mathiaslehmann** [comment]
Hello, works perfectly. Thank you for the effort.

**Comment by erikkastelec** [comment]
Great, closing this.
