### ISSUE TITLE
Entity "sensor.heat_output" shows "Label ist null %" when value is at 0%

### ISSUE THREAD

**Issue by mathiaslehmann** [erikkastelec/hass-WEM-Portal#27]
Hello, the entity "sensor.heat_output" shows "Label ist null %" when value is at 0%. Greater than 0 it works. Don't be surprised, it's always been like this. Maybe you can change something here too. Thank you again for your hard work.

![image](https://user-images.githubusercontent.com/16978467/164688267-ce32d00b-c249-4397-ae52-e82afddf28f0.png)

**Comment by erikkastelec** [comment]
Sure, will add this.

**Comment by erikkastelec** [comment]
Let me know if this fixes it

**Comment by mathiaslehmann** [comment]
Yes it works. Very nice. Thank you very much for the quick correction
