### ISSUE TITLE
any idea how to set device_class: 'temperature'

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#3]
hey @erikkastelec 

I tried but found no way how to set the device_class attribute. I guess that if it is not set for entities that are containing a temperature it is not possible to group them in one history-graph in Lovelace.

One example here:
![image](https://user-images.githubusercontent.com/736311/109208987-4c691480-77ab-11eb-98fe-2bc8e53fe7e8.png)

If you could point me into a direction, I can try to do it and create an PR.

Best,
Dirk

**Comment by erikkastelec** [comment]
I see that device class is not automatically assumed from unit of measurement as I previously thought. Will make the change in the morning and let you know.

**Comment by dm82m** [comment]
I fixed it, just check my PR and merge it if it is okay for you, otherwise give me feedback about things that should be changed

**Comment by erikkastelec** [comment]
Missed that you already did the PR
