### ISSUE TITLE
What to do with this?

### ISSUE THREAD

**Issue by PioSkot** [erikkastelec/hass-WEM-Portal#30]
It worked and suddenly it stopped. Logs:

Logger: homeassistant.setup
Source: custom_components/wemportal/__init__.py:44
Integration: wemportal ([documentation](https://github.com/erikkastelec/hass-WEM-Portal), [issues](https://github.com/erikkastelec/hass-WEM-Portal/issues))
First occurred: 13:44:59 (1 occurrences)
Last logged: 13:44:59

Error during setup of component wemportal
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/wemportal/__init__.py", line 44, in async_setup
    if config[DOMAIN].get(CONF_MODE) == "web":
KeyError: 'wemportal'

**Comment by erikkastelec** [comment]
1. Did you try to restart your Home Assistant instance?
2. Can you provide configuration for wemportal component
3. Did you make any changes/updates?
4. Is wemportal component updated to the latest version?

**Comment by PioSkot** [comment]
Pozwól, że napiszę po polsku, google przetłumaczy... ;)

1. Oczywiście. Kilkukrotnie.
2. Proszę bardzo:
  - platform: wemportal
    language: en
    mode: api
    username: ***@***.***
    password: xxxxxxx
3. Nie.
4. Tak, przestało działać po aktualizacji.

Dziękuję za zainteresowanie.. ;)

P.


śr., 4 maj 2022 o 18:48 Erik Kastelec ***@***.***> napisał(a):

**Comment by erikkastelec** [comment]
2. Is the problem. 
Configuration has changed in the last release. Configuration is **not under sensor** anymore. 
You should move the configuration in separate line (not under sensor) and remove **-platform: **
You need to change your config to:
```
wemportal:
  language: en
  mode: api
  username: your_username
  password: your_password
```

**Comment by erikkastelec** [comment]
Try restarting Home Assistant again.
 If restart does not work I will fix the code and let you know when the update is ready.

**Comment by PioSkot** [comment]
Restarting doesn't help. So I am waiting for the new version.

**Comment by erikkastelec** [comment]
You can try out the new release (1.3.5). Let me know if it helps.
