### ISSUE TITLE
HA log entries 

### ISSUE THREAD

**Issue by floppybl** [erikkastelec/hass-WEM-Portal#34]
Hi,

my HA log is showing some warnings.

`Logger: homeassistant.components.number
Source: components/number/__init__.py:251
Integration: Nummer (documentation, issues)
First occurred: 12:00:24 (6 occurrences)
Last logged: 12:00:24
Entity None (<class 'custom_components.wemportal.number.WemPortalNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.`

`Logger: homeassistant.components.number
Source: components/number/__init__.py:231
Integration: Nummer (documentation, issues)
First occurred: 12:00:24 (1 occurrences)
Last logged: 12:00:24
custom_components.wemportal.number::WemPortalNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.`

Are these known problems and do you know how to fix? Or can I ignore those messages?

Thanks
floppybl

**Comment by erikkastelec** [comment]
Will take a look. Thank you for reporting this
