### ISSUE TITLE
Sensors missing after update to 2022.10

### ISSUE THREAD

**Issue by SKis274** [erikkastelec/hass-WEM-Portal#37]
Hey there,
after updating to the newest homeassistent version I got the following error:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.wemportal
Source: custom_components/wemportal/wemportalapi.py:71
Integration: Weishaupt WEM Portal (documentation, issues)
First occurred: 06:56:35 (1 occurrences)
Last logged: 06:56:35

There was a problem with getting data from WEM Portal. If this problem persists, open an issue at https://github.com/erikkastelec/hass-WEM-Portal/issues
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 71, in fetch_webscraping_data
    self.data = processor.run([wemportal_job])[0]
IndexError: list index out of range
```

There are just a few sensors that still working. Here an example for Vorlauf

![Screenshot_2022-10-06-07-15-13-722_io homeassistant companion android](https://user-images.githubusercontent.com/97400963/194220060-b61a456a-a9d3-4e98-8489-0ed259ec7142.jpg)

Please let me know I you also got problems with the newest version or if I can help you with more information to solve the issue.

Have a nice day 😊

Best regards
Steffen

**Comment by erikkastelec** [comment]
I can reproduce this and will update as soon as I find a solution. Thank you for reporting this.
