### ISSUE TITLE
Unable to install package python-Levenshtein==0.20.*

### ISSUE THREAD

**Issue by mbuchloh** [erikkastelec/hass-WEM-Portal#42]
I'm not shure wether my problem ist correctly addressed here, but everything else works in my home-assistant, operated on raspi.
Since updating HA and WEM-Portal, WEM does not work anymore.

Problem:
Integration error: wemportal - Requirements for wemportal not found: ['python-Levenshtein==0.20.*'].

Log:
Unable to install package python-Levenshtein==0.20.*: error: subprocess-exited-with-error × pip subprocess to install backend dependencies did not run successfully. │ exit code: 1 ╰─> [34 lines of output] Looking in links: https://wheels.home-assistant.io/musllinux/ Collecting cmake Using cached https://wheels.home-assistant.io/musllinux/cmake-3.22.2-cp310-cp310-musllinux_1_2_armv7l.whl (17.8 MB) Collecting ninja Using cached ninja-1.11.1.tar.gz (27 kB) Installing build dependencies: started Installing build dependencies: finished with status 'done' Getting requirements to build wheel: started Getting requirements to build wheel: finished with status 'done' Preparing metadata (pyproject.toml): started Preparing metadata (pyproject.toml): finished with status 'done' Building wheels for collected packages: ninja Building wheel for ninja (pyproject.toml): started Building wheel for ninja (pyproject.toml): finished with status 'error' error: subprocess-exited-with-error × Building wheel for ninja (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [9 lines of output] Traceback (most recent call last): File "/tmp/pip-build-env-l2xtm6um/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 612, in setup cmkr = cmaker.CMaker(cmake_executable) File "/tmp/pip-build-env-l2xtm6um/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 148, in __init__ self.cmake_version = get_cmake_version(self.cmake_executable) File "/tmp/pip-build-env-l2xtm6um/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 103, in get_cmake_version raise SKBuildError( Problem with the CMake installation, aborting build. CMake executable is cmake [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for ninja Failed to build ninja ERROR: Could not build wheels for ninja, which is required to install pyproject.toml-based projects [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × pip subprocess to install backend dependencies did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.

I don't know what version it worked lastes, but my SW is updated quiet often .
Versions: 
Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221102.1

HACS 1.28.3

WEM-Portal 1.3.14 (now 1.3.16)

Anything missing?
Any solutions or hints?

Kind regards
Marcus

**Comment by erikkastelec** [comment]
I added an optional requirement that speeds up a few things, but everything works without it. For now I suggest you go to your configuration folder -> custom_components -> wemportal and edit the `manifest.json` file. You will need to remove the line `"python-Levenshtein==0.20.*"`

This is only a temporary fix and I will look into this and try to find a permanent solution.

**Comment by mbuchloh** [comment]
It works again. Thx a lot.
