### ISSUE TITLE
Wrong Data Type of some (string) Sensors

### ISSUE THREAD

**Issue by iridium2001** [erikkastelec/hass-WEM-Portal#45]
Some Sensors with string values are showing up as float in the the history / charts.
This is the case for e.g.:

wtc-g-betriebsphase_wtc_we0
wtc-g-dreiwegeventil_intern_we0
system-status
hydraulik-betriebsart_hzk0

![image](https://user-images.githubusercontent.com/99202214/201486752-a52eaa5f-122f-4063-9a87-1b3bf60fceb1.png)

**Comment by erikkastelec** [comment]
Should be an easy fix. Expect an update tomorrow.

**Comment by erikkastelec** [comment]
New version has been released.

**Comment by iridium2001** [comment]
Works just perfect! Thanks Erik!
