### ISSUE TITLE
More info possible?

### ISSUE THREAD

**Issue by MRDonnii** [erikkastelec/hass-WEM-Portal#46]
Hello Erik,

Is it possible to get even more info out of this? Like returnflow on heating, gassmoke temp and kwh usage graph?

Great intergration btw.

**Comment by erikkastelec** [comment]
If the data is available in the app or on the website under expert panel, it should be automatically added.

Did you set `mode` to `both` in  your configuration?

**Comment by MRDonnii** [comment]
Hello :)

Im Sorry i was sleeping when i set it up ! I didnt remove the # 

Sorry for the time sir! really a great intergration u made
