### ISSUE TITLE
Data is missing

### ISSUE THREAD

**Issue by marcmanusch** [erikkastelec/hass-WEM-Portal#48]
Following data is missing:

- Vorlaufsolltemperatur
- Rücklauftemperatur

**Comment by erikkastelec** [comment]
1. Were these sensors available before (is this a new problem for you)?
2. How long have you had this issue?

**Comment by imalleyesandears** [comment]
Hello. I am also interested in more data. No matter if I choose api, web or both, I always get the same data available. Is there some way to figure out what should be available?
