### ISSUE TITLE
Error "list index out of range"

### ISSUE THREAD

**Issue by Nighthawk79** [erikkastelec/hass-WEM-Portal#52]
Hello Erik,
since yesterday, i'm getting always an error after the start of HA:

**Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 71, in fetch_webscraping_data
    self.data = processor.run([wemportal_job])[0]
IndexError: list index out of range**

The module by itself is still working, but i'm getting only a small bunch of readings, a lot of readings are "not available".
Is there any change on WEM side?

br
Alex

**Comment by erikkastelec** [comment]
Hi,
are you running the latest version of hass-WEM-Portal. I made a new release yesterday that fixed a similar problem.

**Comment by Nighthawk79** [comment]
Hello Erik,

You are completely right, issu is now solved.
Thank you!
