### ISSUE TITLE
Some sensors (e.g. the boiler flow temperature) have an unchanged value from two days ago.

### ISSUE THREAD

**Issue by PioSkot** [erikkastelec/hass-WEM-Portal#54]
Some sensors (e.g. the boiler flow temperature) have an unchanged value from two days ago. Other sensors function correctly. Is there anything that can be done about this? There is nothing in the logs![wem](https://user-images.githubusercontent.com/94479156/221801373-4057e606-7606-4755-8b97-39cdb6e8f164.png)

**Comment by erikkastelec** [comment]
1. Are you using the latest version (1.4.3), which was released 5 days ago? 
2.  Were there any other changes at that time (Home Assistant update ...), that could cause this?
3. Have you changed WEM website, to see if the values are correct there?

**Comment by PioSkot** [comment]
1. Yes. 
2. yes, I put the system on a new card and restored from a copy. That explains the break. 
3. yes, it is correct

**Comment by erikkastelec** [comment]
Did you try restarting the system yet, if not do that and report back. 
Could you also look for any new entities from this integration. It is possible that the naming or something else changed and a new entity was created.

I will take a closer look at my instance and let you know if I find something.
