### ISSUE TITLE
Unexpected values for Zirkulationspumpe

### ISSUE THREAD

**Issue by 123mariachi123** [erikkastelec/hass-WEM-Portal#56]
Thanks for your great extension!
Basically everything works fine but i get unexpected values for Zirkulationspumpe.
In the wemportal i see either Aus or Ein. So i would expect to get 0 and 1 or Aus and Ein. Both would be fine.
However, what i get is a series of 0 values with short breaks in-between.

Would be nice to get an enhancement here so that the extension gives me 0 and 1.

<img width="546" alt="Bildschirm­foto 2023-04-01 um 19 49 26" src="https://user-images.githubusercontent.com/84244976/229306640-aa6fa55f-337c-4036-8717-c4fd999ee2e9.png">

Thanks a lot for your efforts!
Robert

**Comment by erikkastelec** [comment]
I will investigate this matter. It appears that we encountered similar issues in the past. Solution will be included in the upcoming release.

**Comment by erikkastelec** [comment]
This should be fixed now. If the problem persist please reopen this issue or create a new one.
