### ISSUE TITLE
Plugin loses contact to wem Portal, throws error and doesn’t get back working

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#6]
```
Logger: custom_components.wemportal
Source: custom_components/wemportal/sensor.py:131 
Integration: wemportal (documentation, issues) 
First occurred: 22. März 2021, 16:43:53 (4472 occurrences) 
Last logged: 12:05:01

can't find hydraulik-korrektur_aufheizoptimierung_rücksetzen
can't find heizkreis_heizkreise_heizkreis_1-status
can't find heizkreis_heizkreise_heizkreis_1-warmwassersolltemperatur_aktuell
can't find heizkreis_heizkreise_heizkreis_1-warmwassertemperatur_aktuell
can't find heizkreis_heizkreise_heizkreis_1-pumpe_warmwasser
```

If I restart HA it is back working. That already occurred couple of times.

**Comment by dm82m** [comment]
Mhm currently I don’t get it back to working, not sure if potentially something got changed at the portal. I get also redirected to wemportal.de if I use the Browser to access wemportal.com - no log and nothing in HA log...

**Comment by erikkastelec** [comment]
I think they changed a few things last week, but it didn't break anything for me. 

If you have debug log on it should also give you sensor data of the coordinator. Key error ("can't find x") is raised if there is no data in coordinators data dictionary. So even if the website is down, this should not require a restart, but return to normal after the data is available.

I can't reproduce the issue so it is hard to figure out what could be wrong. I suggest you start hass manually capture the log with `hass -v 2>&1 | tee logfile` and take a look or send it to me. Capturing the log this way will provide scraper info necessary for figuring out what is wrong.

**Comment by dm82m** [comment]
Debug log not showing anything. Will create the log next and post it here

**Comment by dm82m** [comment]
https://gist.github.com/dm82m/52d17c4ee85cd920282eca318120def4

**Comment by dm82m** [comment]
mhm, I guess a renaming of the sensors occured!? debug log looks quite okay as far as I can say.

**Comment by dm82m** [comment]
yes definitely a renaming occurred, had several dead sensors and a lot of new ones. just switched them in my config now and lost a bit of old and historic data, but nevermind. do we close this issue as "wemportal entity renaming and not a problem with the plugin"?

**Comment by erikkastelec** [comment]
Glad that we got to the bottom of this. Gotta keep an eye on wemportal updates in the future.
