### ISSUE TITLE
has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#60]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:597 
Integration: Sensor (documentation, issues) 
First occurred: 15:14:12 (1 occurrences) 
Last logged: 15:14:12

Sensor sensor.heizkreis_heizkreise_heizkreis_2_pumpe_warmwasser has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: Ein (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by dm82m** [comment]
I have no heating pipeline 2, wanted to prove that but can’t as weishaupts engineering excellence strikes back in: „504 Gateway Time-out

Microsoft-Azure-Application-Gateway/v2“

**Comment by dm82m** [comment]
![IMG_4560](https://user-images.githubusercontent.com/736311/234034946-a83034b6-b7d1-4252-8a88-ddb4b35ac90c.png)

**Comment by erikkastelec** [comment]
It looks to me like it is related to #56 . I will add the logic to set it to 1 if it is "Ein"

**Comment by dm82m** [comment]
Release 1.5.1 is somehow broken, not found if I go to releases, not shown in HACS, …

**Comment by erikkastelec** [comment]
Fixed now

**Comment by erikkastelec** [comment]
Closing this, if the problem persists reopen this issue or create a new one.
