### ISSUE TITLE
fix: Add title or placeholder values to setup

### ISSUE THREAD

**Issue by t0rb3n** [erikkastelec/hass-WEM-Portal#63]
With the update to 1.5.x the new way configuration is used. Upon first setup you are greeted with a dialog with two inputs and no
explanation what they are or what values are expected.

This is what the dialog looks like when setting it up. 
![grafik](https://user-images.githubusercontent.com/28067972/234315966-bcd8b09d-e05e-46e7-8a9a-203c987548e3.png)

I think, especially for new users of the integration, some labels (or placeholder values) for the inputs should be there.

**Comment by erikkastelec** [comment]
They should be there. 

![image](https://user-images.githubusercontent.com/34520112/234316761-56047696-3ce4-4a8b-b2b3-f479762eb342.png)

Which version of Home Assistant are you running?

**Comment by erikkastelec** [comment]
Oh, I guess they could be missing as you are running Home Assistant in German. Will look into this.

**Comment by dm82m** [comment]
I am also on HA German and it works as expected on my side.

**Comment by dm82m** [comment]
![IMG_4564](https://user-images.githubusercontent.com/736311/234317995-3f30e556-56b3-49cf-9473-fd4eafe7fd09.png)

**Comment by t0rb3n** [comment]
It's there for me now. Thank you!
