### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Stephan-Fis** [erikkastelec/hass-WEM-Portal#7]
Hi guys,

thanks for the homeassistant-Addon.

I was wondering if it is possible to trigger things from homeassistant to the heater.

For example to activate the additional pump you can activate to circulate the water so that it is hot at the faucet.

greetings Stephan

**Comment by erikkastelec** [comment]
Will look into this, but can't promise anything soon. The problem with that is that I have to find a way to automate every input on the website as every device supports different commands. The Wemportal website is also buggy a lot of times input doesn't send the command to the device.

Thank you for the suggestion and I will let you know if I figure anything out.

**Comment by iridium2001** [comment]
Hi, thanks for your efforts to create this very helpful Home-Assistant add-on. I would also like to second the request from Stephan: it would be super cool if there was a function to trigger the hot-water production "Warmwasser Push". 

[For the circulation pump I already use a workaround: take the power cable out of the heating and connect it with a smart-plug. But this is not an option for the "Warmwasser Push".]

**Comment by erikkastelec** [comment]
Requested feature is available in the latest release, so I will be closing this. If I missed something or if there are any questions, please create a new issue.
