### ISSUE TITLE
Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by mathiaslehmann** [erikkastelec/hass-WEM-Portal#71]
Hello, just encountered a problem.  Any operation, e.g. when selecting the operating mode or when activating hot water push, I get an error.  The current version 1.5.7 is in use.  Mode is set to both.  Thank you very much for the support.

[140294619314448] Object of type bytes is not JSON serializable

**Comment by erikkastelec** [comment]
Thank you for letting me know. I think I introduced an error in release 1.5.4, so you can roll back to 1.5.3 or wait for me to release a fix tomorrow.

**Comment by erikkastelec** [comment]
New release is available. Please reopen if it does not fix the issue for you.
