### ISSUE TITLE
Wird Unit

### ISSUE THREAD

**Issue by radex891** [erikkastelec/hass-WEM-Portal#76]
Hello together,
So far the integration works fine,but i get "kW (W)" instead of just "kW". Has someone already experienced that behavior?

Here is a screenshot:
![image](https://github.com/erikkastelec/hass-WEM-Portal/assets/34899031/6b6d3f59-a957-4fdf-865c-5b0516be231c)

Thanks in advance

**Comment by erikkastelec** [comment]
Missed your issue, but this is expected due to our reliance on information sourced directly from wemportal website, which lists the values in the same manner. Will leave this issue open and come back to it when I refactor the whole code.

**Comment by radex891** [comment]
Thanks for the response and marking this as a bug. Looking forward to the fix.

**Comment by Bertk** [comment]
Looks like there is still a problem with heat pump energy unit: `KWh` shall be `kWh`. I also miss the _overall electrical energy consumption entity [kWh]_ for the device which would eliminate additional integration sensor 

> You can use the [Integration (Riemann sum integral) integration](https://www.home-assistant.io/integrations/integration/#energy) to calculate the energy your device is using

> [!IMPORTANT]
>**The energy dashboard does not accept a sensor using `KWh`** 

<img width="377" alt="image" src="https://github.com/user-attachments/assets/c5082a07-41db-42c7-92bb-d6572e375625">

[Sensor entity](https://developers.home-assistant.io/docs/core/entity/sensor/)

[Understanding Home Energy Management](https://www.home-assistant.io/docs/energy/)
[Integrating individual device energy usage](https://www.home-assistant.io/docs/energy/individual-devices/)

**Comment by Bertk** [comment]
Hi, I used the latest patch and there is still a problem with `unit_of_measurement` const: `KILO_WATT = "kW"`

https://github.com/home-assistant/core/blob/99eb46622371e85b82e4b31686b38721c28048bc/homeassistant/const.py#L683C2-L683C21

<img width="374" alt="image" src="https://github.com/user-attachments/assets/877015ee-02b1-4b05-be7b-a2c1383c6c1a">

**Comment by Kosta-Github** [comment]
https://github.com/erikkastelec/hass-WEM-Portal/pull/104 should fix this

**Comment by erikkastelec** [comment]
Thanks to @Kosta-Github this issue seems to be fixed and is released in version 1.5.11
