### ISSUE TITLE
Energy Usage

### ISSUE THREAD

**Issue by KallerTobias** [erikkastelec/hass-WEM-Portal#79]
Hello, 

is it possible to get the Data of Energy Usage in kWh (Gas or Electricity) as well?
I would like to implement the data in the energy dashboard of Home Assistant. 

Kind Regards,

Tobias

**Comment by dm82m** [comment]
Please check this thread: https://github.com/erikkastelec/hass-WEM-Portal/issues/19

**Comment by KallerTobias** [comment]
Thanks, 
seem to me that, i was not able to read the manual correctly :-(
