### ISSUE TITLE
Decrease scan_interval minimum value

### ISSUE THREAD

**Issue by simonstamm** [erikkastelec/hass-WEM-Portal#8]
Hey @erikkastelec,

thanks a lot for creating this Home Assistant integration! I'm currently using my own Docker solution which scrapes every 30 seconds. I saw in #1 that there was a request from Weishaupt to have at least 30 minutes interval so you set the minimum to 15 mins:
https://github.com/erikkastelec/hass-WEM-Portal/blob/fd3967822e4d550c2d7f4f578a067bcc6eb2fa43/custom_components/wemportal/sensor.py#L63

I agree with setting the default to 30 minutes but would ask you if you could reduce the minimum value to 1 minute (or at least 5 minutes), because I have some automations which rely on fresh data and would love to switch to your integration.

Imho it's not our problem that Weishaupt isn't providing the customer a better API since we pay a lot of money for the web interface *and* the heat pump.

**Comment by dm82m** [comment]
Hey @simonstamm in general I agree with your point that it’s not our Problem. But I already got bans from Weishaupt so it makes less sense to generally decrease the minimum. If you want to risk that on your own, you could just change it in your local copy of the plug-in. Best dirk

**Comment by simonstamm** [comment]
Yea, I could easily change it locally, but I do not prefer these solutions since I have to merge it again after every update. :-) Maybe it's then worth documenting it that you risk a ban with setting anything lower than 30 minutes within the README but don't restrict the user.

**Comment by simonstamm** [comment]
@dm82m I created #9 which can solve the perfomance issues Weishaupt currently is having with it's ASPX WEM Portal.

**Comment by dm82m** [comment]
Yes already saw that. Could be relatively easy switching to this endpoint instead of scraping and I am pretty sure also the performance issue and banning problem is solved. Only question is: who is having some time doing it 🤪

**Comment by erikkastelec** [comment]
I agree that the minimum interval can be up to the user so I will remove it. I will also adjust some sleep times when scrapping, which are not necessary to speed things up.  #9 looks promising, so I will try it out.
