### ISSUE TITLE
Weishaupt Pump Control

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#81]
Hey guys,

We live in a house build 2019. we have a weishaupt gas heating and a Grundfos alpha2 pump for heating circulation. Each year we have the problem that the pump is stuck. It got replaced last year but still the same issue this year. This problem occurs after summer when we turn on heating. Do you know if there is a feature that is letting the pump run for a minute a day in summer mode to prevent getting stuck. Or do you have other ideas? The installation company tells me that I have to run the pump manually each month. But to be honest, that can’t be the case, right?

thanks for your thoughts

**Comment by boysim** [comment]
hi, 
You need to update the WEM SG on your WTC.

kind regards

**Comment by dm82m** [comment]
@boysim how can this update be achieved? through wemportal? directly on the device? or only by a mechanic with additional hardware/software?

**Comment by dm82m** [comment]
Weishaupt told me that this function is currently not existent. It is only available for the pump inside the heating itself but not for the external one for underfloor heating pump. They said that maybe there will be a firmware update end of 2024.
So it seems that the only way is to externally power the pump in summer and ensure that it runs once each week.

**Comment by boysim** [comment]
@dm82m which software version do you currently have? update is done by putting all the update files on the sd card..

**Comment by dm82m** [comment]
can you point me to where I can check that?

**Comment by boysim** [comment]
please send me an email on simon.pauwels-------(@)-------weishaupt.be also remove al dashes and brackets from the email 😉

**Comment by dm82m** [comment]
@boysim can you please check your spam folder 🫢

**Comment by dm82m** [comment]
@boysim can you Check Your Mails or Spam please. 😁

**Comment by ghenzler** [comment]
I have a Grundfos pump but only for hot water as far as I'm aware. If you really need this pump running during summer in a regular interval, you can probably just use this integration to set "Heizkreis 1-Betriebsart" to "Heizen" and "Heizkreis 1-Normal" (or whichever temperature is active at the time) to a higher temp to ensure it starts heating... you should be able to do this in a custom automation without any change to this plugin.

**Comment by dm82m** [comment]
Got it solved via firmware upgrade of the Weishaupt system. Just runs the pump shortly every day at 12 o clock.

**Comment by dm82m** [comment]
@boysim can you please check your business mail. thank you!
