### ISSUE TITLE
Integration stopped working.

### ISSUE THREAD

**Issue by PioSkot** [erikkastelec/hass-WEM-Portal#82]
Why doesn't it work?

LOG:
Logger: custom_components.wemportal
Source: custom_components/wemportal/coordinator.py:67
Integration: Weishaupt WEM Portal (documentation, issues)
First occurred: 12 listopada 2023 21:36:22 (2879 occurrences)
Last logged: 13:49:45

Error fetching data from wemportal
Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 195, in api_login
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.wemportal.com/app/Account/Login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/wemportalapi.py", line 88, in fetch_data
    self.api_login()
  File "/config/custom_components/wemportal/wemportalapi.py", line 208, in api_login
    raise ForbiddenError(
custom_components.wemportal.exceptions.ForbiddenError: WemPortal forbidden error: Server returned internal status code:  and message: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wemportal/coordinator.py", line 67, in _async_update_data
    x = await self.hass.async_add_executor_job(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wemportal/wemportalapi.py", line 142, in fetch_data
    raise WemPortalError from exc
custom_components.wemportal.exceptions.WemPortalError

**Comment by erikkastelec** [comment]
Hi, 

have you checked:

1.  that the data is accessible via wemportal website and wem mobile app?
2.  you have an active subscription
3. device is connected to the internet

If you checked all of the above, I suggest you try reloading the component by going to Settings -> Devices & Services -> Weishaupt WEM Portal and clicking three dots next to configure button for integration entry and selecting Reload in a drop down menu.

Hope this helps and let me know if the problem persists.

**Comment by PioSkot** [comment]
Hi, 

1 No.  If I connect from any IP there is no problem connecting. But if I do it from the network the cooker is plugged into - I get a "403 Forbidden Microsoft-Azure-Application-Gateway/v2" error. It's as if it's my IP that's being blocked by WEMPortal. 
2 What subscription is this about? It has always worked... ;) I'm assuming there might be a problem here. 
3. yes.

**Comment by erikkastelec** [comment]
This error typically indicates that your IP was blocked due to an excessive number of requests in a short period. Some users experienced this issue when their license expired (see issue #78), and others encountered it when their device was offline. I haven't yet resolved all these issues, as reproducing some of them is quite challenging.

    It is necessary to renew the subscription to the Wem portal every five years. If the data on the website is up-to-date and the app functions outside of your network, then your subscription is still active.

I suggest turning off your modem for a minute to obtain a new dynamic IP from your ISP. If you have a static IP, you will need to contact Weishaupt for them to unblock it.

I apologize for the inconvenience and am working to resolve these issues promptly to prevent future occurrences.

**Comment by PioSkot** [comment]
Thank you for your response and efforts. Bows to the ground for what you are doing.
