### ISSUE TITLE
403 Client Error: Forbidden for GET: https://www.wemportal.com/app/device/Read

### ISSUE THREAD

**Issue by stehille** [erikkastelec/hass-WEM-Portal#84]
After a successful login (status: 200 OK), I get this error message. I use Postman for testing. Can someone tell me what I'm doing wrong?

**Comment by erikkastelec** [comment]
You have to set appropriate headers.
`Content-Type: application/json`
`User-Agent: WeishauptWEMApp`
`X-Api-Version: 2.0.0.0`

Recently, I encountered another issue while using Postman. I received a 200 OK response when sending a GET request to device/read, but the content was empty. If you experience this issue, I suggest trying Insomnia, which worked well for me.

**Comment by stehille** [comment]
Hello Erik, thank you for the quick answer and the solution with the header. That was the trick! The content is available to me. :-)
