### ISSUE TITLE
Sensors Missing after Update to 2024.4.0bx and HA OS 12.2.rc1

### ISSUE THREAD

**Issue by maddinhome** [erikkastelec/hass-WEM-Portal#85]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.wemportal
Quelle: custom_components/wemportal/wemportalapi.py:122
Integration: Weishaupt WEM Portal (Dokumentation, Probleme)
Erstmals aufgetreten: 06:34:06 (6 Vorkommnisse)
Zuletzt protokolliert: 06:53:41

[Errno 30] Read-only file system

The API function still works, but as soon as I select both, the sensors are no longer available. But it would be nice if both worked. To troubleshoot the problem, I reloaded the integration and logged in again. Unfortunately, that didn't help. Thank you for this integration, which is much better than the Weishaupt portal.

**Comment by maddinhome** [comment]
maybe it has something to do with this:

https://github.com/home-assistant/operating-system/issues/3278

**Comment by erikkastelec** [comment]
I'll try to reproduce the bug and let you know if I need any additional info.

**Comment by maddinhome** [comment]
"api" works.... but only 13 entities, "web" and "both" in configuration don't work

**Comment by maddinhome** [comment]
using "ha os update --version 12.1" in a terminal...

fix it for me.... look here: 

https://github.com/home-assistant/operating-system/issues/3278#issuecomment-2032346337

**Comment by erikkastelec** [comment]
If I understand correctly, the issue was fixed by the Home Assistant update and we can close this?

**Comment by maddinhome** [comment]
yes thank you

**Comment by maddinhome** [comment]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.wemportal
Quelle: custom_components/wemportal/wemportalapi.py:122
Integration: Weishaupt WEM Portal (Dokumentation, Probleme)
Erstmals aufgetreten: 09:26:42 (2 Vorkommnisse)
Zuletzt protokolliert: 09:27:34

[Errno 30] Read-only file system

Sorry, but I have to open the ticket again. With the HA OS release 12.2rc2 the same problem occurs again.
