### ISSUE TITLE
Sensors Missing after Update to 2024.4.2 and HA OS 12.2.rc2

### ISSUE THREAD

**Issue by maddinhome** [erikkastelec/hass-WEM-Portal#86]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.wemportal
Quelle: custom_components/wemportal/wemportalapi.py:122
Integration: Weishaupt WEM Portal (Dokumentation, Probleme)
Erstmals aufgetreten: 09:26:42 (2 Vorkommnisse)
Zuletzt protokolliert: 09:27:34

[Errno 30] Read-only file system

Sorry, but I have to open the ticket again. With the HA OS release 12.2rc2 the same problem occurs again.

The API function still works, but as soon as I select both, the sensors are no longer available. But it would be nice if both worked.

A rollback to HA OS 12.1 and it works again.

Core 2024.4.2
Supervisor 2024.04.1
Operating System 12.1 (after rollback)
Frontend 20240404.1

**Comment by erikkastelec** [comment]
I see that this is listed as a known issue under Home Assistant OS 12.2.rc1 release and should be fixed in Supervisor version 2024.04.0, which you already have. For the time being I suggest you stick to official non beta releases. 

If the problem persists with the next non beta release, let me know. For now I will leave this issue open, but won't be working on this as it seems to be an issue with  Home Assistant and not this specific custom integration.

**Comment by maddinhome** [comment]
The error now also occurs in the final version... I changed the title of the post.

Rollback to 12.1 and it works again.

Maybe it depends on the new Docker version?

**Comment by dm82m** [comment]
@erikkastelec can confirm this issue on my side. Core 2024.4.2 and OS 12.2

**Comment by erikkastelec** [comment]
Ok, will try to find a fix tomorrow. Thanks for looking into it.

**Comment by dm82m** [comment]
Solution is already at place: ensure to be on supervisor 2024.4.0 and then run `ha core rebuild` in a terminal or the ssh addon. Details can be found here: https://github.com/home-assistant/supervisor/issues/4996#issuecomment-2033200027

**Comment by mathiaslehmann** [comment]
After "ha core rebuild" Its work greate again. Thanks @dm82m

**Comment by maddinhome** [comment]
After rebuilding the core it worked again. That's probably the solution... Thanks @erikkastelec  and  @dm82m

**Comment by ChicktheChicken** [comment]
Thank you for ur fast solution
