### ISSUE TITLE
Integration wird nicht mehr geladen [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by mathiaslehmann** [erikkastelec/hass-WEM-Portal#87]
Hallo,
nach dem Update auf Home Assistant OS 12.2 wird die Integration nicht mehr geladen. Ich habe folgenden Fehler im Log gefunden.

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.wemportal
Quelle: custom_components/wemportal/wemportalapi.py:122
Integration: Weishaupt WEM Portal (Dokumentation, Probleme)
Erstmals aufgetreten: 19:32:58 (3 Vorkommnisse)
Zuletzt protokolliert: 19:37:54

[Errno 30] Read-only file system

**Comment by dm82m** [comment]
Duplicate of #86
